# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MAFNews' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MAFNews
  pod 'ObjectMapper', '~> 3.4'
  pod 'Alamofire'

  target 'MAFNewsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MAFNewsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
